-- Run in caller BEGIN/ROLLBACK. No persistent staff, prices, trades or mail sends.
DO $$
DECLARE a uuid:=gen_random_uuid();s uuid:=gen_random_uuid();o uuid:=gen_random_uuid();p uuid:=gen_random_uuid();c uuid:=gen_random_uuid();
 i uuid;n uuid;r jsonb;k uuid:=gen_random_uuid();marker text:=gen_random_uuid()::text;v integer;
BEGIN
 IF has_function_privilege('anon','public.b2b_initial_operations(uuid)','EXECUTE') OR has_function_privilege('authenticated','public.b2b_ops_eligible_staff(uuid,text)','EXECUTE') THEN RAISE EXCEPTION 'public operations RPC';END IF;
 INSERT INTO auth.users(id,email,aud,role,email_confirmed_at,created_at,updated_at) SELECT u,u||'@example.invalid','authenticated','authenticated',now(),now(),now() FROM unnest(ARRAY[a,s,o,p,c])u;
 INSERT INTO public.user_profiles(id,email,name,role,status) VALUES(a,a||'@example.invalid','QA initial admin','admin','active'),(s,s||'@example.invalid','QA inquiry','inquiry_staff','active'),(o,o||'@example.invalid','QA order','order_staff','active'),(p,p||'@example.invalid','QA product','product_staff','active');
 INSERT INTO public.customer_accounts(id,email,name) VALUES(c,c||'@example.invalid','QA customer');
 r:=public.b2b_submit_inquiry(repeat('a',64),gen_random_uuid(),repeat('b',64),jsonb_build_object('kind','export_rfq','company',marker,'contact_name','QA','email','form@example.invalid','submitted_by',c));
 i:=(r->>'id')::uuid;
 SELECT id INTO n FROM public.b2b_notification_outbox WHERE inquiry_id=i;
 INSERT INTO public.b2b_email_deliveries(notification_id,state) VALUES(n,'failed');
 r:=public.b2b_ops_snapshot(s,'work',marker,'mail_failed');
 IF (r->>'total')::integer<>1 THEN RAISE EXCEPTION 'actual mail failure missing';END IF;
 r:=public.b2b_ops_snapshot(o,'work',marker,'mail_failed');
 IF (r->>'total')::integer<>0 THEN RAISE EXCEPTION 'mail leaked to order role';END IF;
 PERFORM public.b2b_ops_plan(a,'inquiry',i,1,s,now()-interval '1 minute','QA actual handoff',k,repeat('c',64));
 UPDATE auth.users SET banned_until=now()+interval '1 hour' WHERE id=s;
 r:=public.b2b_ops_snapshot(a,'work',marker,'reassignment');
 IF (r->>'total')::integer<>1 OR (SELECT assigned_to FROM public.commercial_inquiries WHERE id=i)<>s THEN RAISE EXCEPTION 'reassignment missing or historical assignment erased';END IF;
 IF EXISTS(SELECT 1 FROM jsonb_array_elements(r->'staff') x WHERE x->>'id'=s::text) THEN RAISE EXCEPTION 'banned staff in directory';END IF;
 BEGIN PERFORM public.b2b_ops_plan(a,'inquiry',i,2,s,NULL,'QA blocked assignment',gen_random_uuid(),repeat('d',64));RAISE EXCEPTION 'banned assignee';EXCEPTION WHEN invalid_parameter_value THEN NULL;END;
 BEGIN PERFORM public.b2b_initial_operations(s);RAISE EXCEPTION 'banned snapshot';EXCEPTION WHEN insufficient_privilege THEN NULL;END;
 UPDATE auth.users SET banned_until=NULL,email_confirmed_at=NULL WHERE id=s;
 BEGIN PERFORM public.b2b_ops_plan(a,'inquiry',i,2,s,NULL,'QA unverified assignment',gen_random_uuid(),repeat('d',64));RAISE EXCEPTION 'unverified assignee';EXCEPTION WHEN invalid_parameter_value THEN NULL;END;
 UPDATE auth.users SET email_confirmed_at=now() WHERE id=s;
 UPDATE public.user_profiles SET role='order_staff' WHERE id=s;
 r:=public.b2b_ops_snapshot(a,'work',marker,'','reassign');
 IF (r->>'total')::integer<>1 THEN RAISE EXCEPTION 'changed role reassignment missing';END IF;
 UPDATE public.user_profiles SET role='inquiry_staff' WHERE id=s;
 r:=public.b2b_ops_snapshot(a,'work',marker,'','reassign');
 IF (r->>'total')::integer<>0 THEN RAISE EXCEPTION 'eligible staff false reassignment';END IF;
 UPDATE public.b2b_email_deliveries SET state='sending',lease_until=now()-interval '1 second' WHERE notification_id=n;
 r:=public.b2b_ops_snapshot(s,'work',marker,'mail_unknown');
 IF (r->>'total')::integer<>1 OR (SELECT state FROM public.b2b_email_deliveries WHERE notification_id=n)<>'sending' THEN RAISE EXCEPTION 'expired lease missing or GET mutated delivery';END IF;
 UPDATE public.b2b_email_deliveries SET state='uncertain',lease_until=NULL WHERE notification_id=n;
 r:=public.b2b_initial_operations(s);
 IF (r->'counts'->>'mail_unknown')::int<1 OR (r->'metrics'->>'mine')::int<1 OR (r->'metrics'->>'overdue')::int<1 THEN RAISE EXCEPTION 'initial priorities missing';END IF;
 r:=public.b2b_initial_operations(p);
 IF r->'counts'<>'{}'::jsonb OR (r->'metrics'->>'active')::int<>0 OR r::text LIKE '%form@example.invalid%' THEN RAISE EXCEPTION 'product role trade leak';END IF;
 BEGIN PERFORM public.b2b_initial_operations(c);RAISE EXCEPTION 'customer snapshot';EXCEPTION WHEN insufficient_privilege THEN NULL;END;
 UPDATE public.b2b_email_deliveries SET state='queued' WHERE notification_id=n;
 r:=public.b2b_ops_snapshot(s,'work',marker,'mail_queued');
 IF (r->>'total')::integer<>1 THEN RAISE EXCEPTION 'queued actual mail hidden';END IF;
 UPDATE public.b2b_email_deliveries SET state='accepted' WHERE notification_id=n;
 r:=public.b2b_ops_snapshot(s,'work',marker,'mail_unknown');
 IF (r->>'total')::integer<>0 THEN RAISE EXCEPTION 'SMTP accepted falsely pending';END IF;
 SELECT count(*) INTO v FROM public.b2b_email_events WHERE notification_id=n;
 IF v<>0 THEN RAISE EXCEPTION 'read-only operations caused mail event';END IF;
END $$;
