'use client';
import {useState} from 'react';
import type {CrmInquiry,QuoteDraft,ReviewInput} from '@/lib/crm/types';
const field='mt-1 w-full rounded border border-stone-600 bg-stone-950 p-2 text-sm text-white';
const initial:ReviewInput={stock_status:'unreviewed',documents_status:'unreviewed',lead_time_note:'',review_note:'',change_reason:'신규 검토 초안',consultation_status:'not_required',consultation_note:'',adjustments:[]};
export default function QuoteEditor({inquiry,latest,busy,save}:{inquiry:CrmInquiry;latest?:QuoteDraft;busy:boolean;save:(body:Record<string,unknown>)=>Promise<boolean>}) {
  const [review,setReview]=useState<ReviewInput>(latest?.snapshot.review||initial);
  const [prices,setPrices]=useState<Record<string,{amount:string;reason:string}>>(Object.fromEntries((latest?.snapshot.review.adjustments||[]).map(a=>[a.product_id,{amount:a.unit_net_usd,reason:a.reason}])));
  return <form onSubmit={e=>{e.preventDefault();void save({action:'quote',base_id:latest?.id||null,review:{...review,adjustments:Object.entries(prices).filter(([,v])=>v.amount.trim()).map(([product_id,v])=>({product_id,unit_net_usd:v.amount.trim(),reason:v.reason}))}});}} className="space-y-4 rounded-xl border border-amber-800 bg-stone-900 p-5">
    <h3 className="text-lg font-bold">견적 초안 {latest?'새 버전':'만들기'}</h3><p className="text-xs leading-6 text-stone-400">현재 서버 가격·환율·포장을 고정해 저장합니다. 미확정 자료는 보완 목록으로 남고 금액은 생성되지 않습니다. 고객에게 발행되는 PI가 아닙니다.</p>
    <div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">공급 가능 수량 검토<select value={review.stock_status} onChange={e=>setReview({...review,stock_status:e.target.value as ReviewInput['stock_status']})} className={field}><option value="unreviewed">미검토</option><option value="available">공급 가능 확인</option><option value="unavailable">공급 불가·조정 필요</option></select></label><label className="text-sm">요구 서류 검토<select value={review.documents_status} onChange={e=>setReview({...review,documents_status:e.target.value as ReviewInput['documents_status']})} className={field}><option value="unreviewed">미검토</option><option value="ready">준비 확인 / 요구 없음</option><option value="missing">자료 보완 필요</option></select></label></div>
    <label className="block text-sm">납기 검토 근거<input maxLength={1000} value={review.lead_time_note} onChange={e=>setReview({...review,lead_time_note:e.target.value})} className={field}/></label>
    <label className="block text-sm">공급·FOB 비용·서류 검토 메모<textarea maxLength={5000} rows={3} value={review.review_note} onChange={e=>setReview({...review,review_note:e.target.value})} className={field}/></label>
    <details><summary className="cursor-pointer text-sm text-amber-300">가격 조정 제안 (필요할 때만)</summary><p className="mt-3 text-xs text-stone-400">기본 FOB 비용을 자동 가산하지 않습니다. 변경 단가와 사유를 기록하고 사전 안내·협의 근거를 남겨 주세요.</p><div className="mt-4 space-y-3">{inquiry.items.map(i=><fieldset key={i.product_id} className="rounded border border-stone-700 p-3"><legend className="max-w-full break-words px-2 text-xs">{i.product_name}</legend><label className="block text-xs">제안 단가 USD / CTN<input inputMode="decimal" aria-label={i.product_id+' 제안 단가'} value={prices[i.product_id]?.amount||''} onChange={e=>setPrices({...prices,[i.product_id]:{reason:prices[i.product_id]?.reason||'',amount:e.target.value}})} className={field}/></label><label className="mt-3 block text-xs">품목 조정 사유<input maxLength={1000} value={prices[i.product_id]?.reason||''} onChange={e=>setPrices({...prices,[i.product_id]:{amount:prices[i.product_id]?.amount||'',reason:e.target.value}})} className={field}/></label></fieldset>)}</div>
    <label className="mt-4 block text-sm">가격 조정 협의 상태<select value={review.consultation_status} onChange={e=>setReview({...review,consultation_status:e.target.value as ReviewInput['consultation_status']})} className={field}><option value="not_required">조정 없음</option><option value="pending">사전 안내 대기</option><option value="communicated">변경안 안내 기록</option><option value="agreed">협의 완료 기록</option></select></label>
    <label className="mt-3 block text-sm">안내·협의 근거 (메일·통화 일시와 내용)<textarea maxLength={2000} value={review.consultation_note} onChange={e=>setReview({...review,consultation_note:e.target.value})} className={field}/></label><p className="mt-2 text-xs text-stone-400">담당자가 남기는 협의 기록이며 고객의 온라인 PI 수락을 대신하지 않습니다.</p></details>
    <label className="block text-sm">이번 초안 작성·변경 사유 *<input required minLength={3} maxLength={1000} value={review.change_reason} onChange={e=>setReview({...review,change_reason:e.target.value})} className={field}/></label>
    <button disabled={busy} className="rounded bg-amber-400 px-5 py-3 font-bold text-stone-950 disabled:opacity-40">{busy?'저장 중…':'서버 가격으로 초안 저장'}</button>
  </form>;
}
