import Link from 'next/link';
import {serverLanguage} from '@/lib/i18n/server';
import {getBusinessSettings} from '@/lib/business-settings-server';
import BusinessContact from '@/components/layout/BusinessContact';
export default async function Page(){
 const {language,text,href}=await serverLanguage(),{profile}=await getBusinessSettings();
 return <main className="mx-auto max-w-4xl px-5 py-12"><p className="text-sm font-bold text-green-800">SONGFOOD · KOREAN FOOD SUPPLY</p><h1 className="mt-4 text-3xl font-bold">{text('송영민푸드 소개','About Song Youngmin Food')}</h1>
 <p className="mt-6 leading-8">{text('국내 도매고객과 대용량 식료품을 찾는 개인, 해외 바이어를 위한 식품 카탈로그입니다. 개인도 이메일 인증으로 가입할 수 있으며 사업자번호는 선택입니다.','A food catalogue for domestic wholesale customers, individual bulk buyers and overseas buyers. Join with email verification; company information and a business registration number are optional.')}</p>
 <div className="mt-8 grid gap-5 md:grid-cols-2"><section className="rounded-xl border bg-white p-6"><h2 className="text-xl font-bold">{text('국내 도매·대용량 구매','Domestic bulk orders')}</h2><p className="mt-4 leading-7">{text('상품별 EA·BOX·CTN 포장과 최소구매수량을 확인하세요. 승인된 가격은 로그인 후 확인합니다. 배송비·공급 조건을 검토하고 고객이 확정 조건을 수락한 뒤 안내된 계좌로 입금합니다.','Check EA, BOX and CTN packaging and minimum quantities. Approved prices are available after login. Supply and delivery terms are reviewed before you accept the final terms and pay by bank transfer.')}</p><Link href={href('/shop')} className="mt-5 inline-block py-3 underline">{text('국내 상품 보기','Domestic catalogue')}</Link></section>
 <section className="rounded-xl border bg-white p-6"><h2 className="text-xl font-bold">Export RFQ · FOB</h2><p className="mt-4 leading-7">{text('해외 기준가는 국내 도매가에서 부가세 10%를 제외한 FOB 조건입니다. 국내 운송·수출통관·본선 적재 비용은 해당 가격에 포함하여 운영하며 수량·항구·선적 조건에 따라 조정될 수 있습니다. 발행 문서는 Proforma Invoice이며 최종 Commercial Invoice가 아닙니다.','Export reference prices exclude 10% Korean VAT and use FOB terms. Domestic transport, export clearance and loading costs are included, subject to adjustment for quantity, port and shipment requirements. Issued quotations are Proforma Invoices, not final Commercial Invoices.')}</p><Link href={href('/rfq')} className="mt-5 inline-block py-3 underline">Request a quotation</Link></section></div>
 <section className="mt-10"><h2 className="text-xl font-bold">{text('회사·문의 정보','Business and contact details')}</h2><BusinessContact profile={profile} language={language}/></section>
 <p className="mt-8 text-sm leading-7 text-stone-700">{text('원산지·인증·성분·유통기한·보관 방법은 상품별 자료를 확인하세요. 인증은 상품·제조시설·유효기간별 근거 확인이 필요합니다. 주류는 판매 자격·성인 확인·도착국 규정 검토 후 공급 가능 여부를 안내합니다.','Check product-specific origin, certification, ingredients, shelf life and storage information. Certifications require evidence for the product, facility and validity period. Alcohol supply requires review of seller eligibility, age verification and destination rules.')}</p>
 </main>;
}
