jest.mock('@/lib/admin-auth',()=>({getStaffIdentity:jest.fn()}));
jest.mock('@/lib/supabase-admin',()=>({supabaseAdmin:{rpc:jest.fn()}}));
jest.mock('@/lib/request-security',()=>({...jest.requireActual('@/lib/request-security'),rateLimit:jest.fn(),digest:jest.fn().mockResolvedValue('a'.repeat(64))}));
import {getStaffIdentity} from '@/lib/admin-auth';
import {supabaseAdmin} from '@/lib/supabase-admin';
import {GET} from '@/app/api/admin/operations/work/route';
import {GET as documents} from '@/app/api/admin/operations/documents/route';
import {GET as contacts} from '@/app/api/admin/operations/contacts/route';
import {POST} from '@/app/api/admin/operations/plan/route';
import {GET as history} from '@/app/api/admin/operations/history/[kind]/[id]/route';
const id='11111111-1111-4111-8111-111111111111';
const req=(body:object,origin='https://example.invalid')=>new Request('https://example.invalid/api/admin/operations/plan',{method:'POST',headers:{'Content-Type':'application/json',origin},body:JSON.stringify(body)});
beforeEach(()=>{jest.clearAllMocks();process.env.NEXT_PUBLIC_APP_URL='https://example.invalid';jest.mocked(getStaffIdentity).mockResolvedValue({id,email:'x@example.invalid',role:'order_staff'});jest.mocked(supabaseAdmin.rpc).mockResolvedValue({data:{total:4,items:[]},error:null} as never);});
test('unauthenticated staff stops before database',async()=>{jest.mocked(getStaffIdentity).mockResolvedValue(null);expect((await GET(new Request('https://example.invalid'))).status).toBe(403);expect(supabaseAdmin.rpc).not.toHaveBeenCalled();});
test('work uses server identity and normalized parameters',async()=>{const r=await GET(new Request('https://example.invalid?q=abc&page=2&kind=order'));expect(r.status).toBe(200);expect(supabaseAdmin.rpc).toHaveBeenCalledWith('b2b_ops_snapshot',expect.objectContaining({p_actor:id,p_page:2,p_q:'abc',p_kind:'order'}));});
test.each([documents,contacts])('domain role cannot query protected datasets',async handler=>{expect((await handler(new Request('https://example.invalid'))).status).toBe(403);expect(supabaseAdmin.rpc).not.toHaveBeenCalled();});
test('stale work plan conflict maps 409 and rejects CSRF',async()=>{const body={kind:'order',id,revision:2,assigned_to:null,due_at:null,message:'다음 행동',request_key:id};expect((await POST(req(body,'https://evil.invalid'))).status).toBe(403);expect(supabaseAdmin.rpc).not.toHaveBeenCalled();jest.mocked(supabaseAdmin.rpc).mockResolvedValue({data:null,error:{code:'40001'}} as never);expect((await POST(req(body))).status).toBe(409);});
test('cross-domain work plan rejected before RPC',async()=>{expect((await POST(req({kind:'inquiry',id,revision:2,assigned_to:null,due_at:null,message:'다음 행동',request_key:id}))).status).toBe(403);expect(supabaseAdmin.rpc).not.toHaveBeenCalled();});
test('plan cannot override authenticated actor, due server normalized',async()=>{const r=await POST(req({kind:'order',id,revision:2,assigned_to:id,due_at:'2026-10-04T12:00:00+09:00',message:'은행 대조 후 출고',request_key:id,actor_id:'spoof'}));expect(r.status).toBe(200);expect(supabaseAdmin.rpc).toHaveBeenCalledWith('b2b_ops_plan',expect.objectContaining({p_actor:id,p_due:'2026-10-04T03:00:00.000Z',p_hash:'a'.repeat(64)}));});
test('history cannot expose another domain',async()=>{expect((await history(new Request('https://example.invalid'),{params:Promise.resolve({kind:'inquiry',id})})).status).toBe(403);expect(supabaseAdmin.rpc).not.toHaveBeenCalled();});
test('history paginates under authenticated role',async()=>{expect((await history(new Request('https://example.invalid?page=3'),{params:Promise.resolve({kind:'order',id})})).status).toBe(200);expect(supabaseAdmin.rpc).toHaveBeenCalledWith('b2b_ops_history',{p_actor:id,p_kind:'order',p_id:id,p_page:3});});
test('DB failure returns 503 without counts or sensitive provider error',async()=>{jest.mocked(supabaseAdmin.rpc).mockResolvedValue({data:null,error:{code:'XX999',message:'secret details'}} as never);const r=await GET(new Request('https://example.invalid')),b=await r.json();expect(r.status).toBe(503);expect(b).not.toHaveProperty('total');expect(JSON.stringify(b)).not.toContain('secret details');});
