import {HANDOVER_CHECKS,canReview,assessHandover,type HandoverData} from '@/lib/launch/handover';
import {parseHandover,handoverError,handoverSnapshot} from '@/lib/launch/handover-server';
import {GET,PUT} from '@/app/api/admin/handover/route';
import {opsStaff} from '@/lib/operations/repository';
import {supabaseAdmin} from '@/lib/supabase-admin';
import {rateLimit,ApiError} from '@/lib/request-security';
import {launchStatus} from '@/lib/launch/repository';
import {releaseSnapshot} from '@/lib/launch/releases';
jest.mock('@/lib/operations/repository',()=>({opsStaff:jest.fn()}));
jest.mock('@/lib/supabase-admin',()=>({supabaseAdmin:{rpc:jest.fn()}}));
jest.mock('@/lib/launch/repository',()=>({launchStatus:jest.fn()}));
jest.mock('@/lib/launch/releases',()=>({releaseSnapshot:jest.fn()}));
jest.mock('@/lib/request-security',()=>({...jest.requireActual('@/lib/request-security'),rateLimit:jest.fn()}));
const id='00000000-0000-4000-8000-000000000801',hash='a'.repeat(64);
const data:HandoverData={actor_id:id,role:'admin',basis:Object.fromEntries(HANDOVER_CHECKS.map(c=>[c.id,hash])) as HandoverData['basis'],staff:[{id,name:'Chief',role:'admin'}],reviews:[],events:[]};
const body={check_id:'auth_mail',revision:0,basis:hash,result:'passed',notes:'Actual inbox and link have been checked',reference_id:null,received:true};
const controls={owner_id:id,owner:'Chief',response_minutes:30,revision:1,updated_at:'2026-10-04',orders_paused:false,inquiries_paused:false,pi_paused:false};
function request(value:unknown=body){return new Request('https://example.invalid/api/admin/handover',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(value)});}
beforeEach(()=>{jest.clearAllMocks();jest.mocked(opsStaff).mockResolvedValue({id,role:'admin',email:''});jest.mocked(supabaseAdmin.rpc).mockResolvedValue({data,error:null} as never);jest.mocked(launchStatus).mockResolvedValue({controls,checks:[],facts:{},events:[],manual_checks:[],staff:[]} as never);jest.mocked(releaseSnapshot).mockResolvedValue({products:[]} as never);});
test('fixed review permissions preserve business roles',()=>{expect(canReview('access','order_staff')).toBe(true);expect(canReview('domestic','inquiry_staff')).toBe(false);expect(canReview('operations','product_staff')).toBe(false);});
test.each([{actor_id:'spoof'},{revision:-1},{revision:0.5},{basis:'bad'},{received:'true'},{result:'ready'},{notes:'short'},{notes:'<script>invalid text</script>'},{reference_id:'invalid'}])('invalid/extra input rejected %j',patch=>{expect(()=>parseHandover({...body,...patch})).toThrow(ApiError);});
test('actual receipt and completed transaction references are required',()=>{expect(()=>parseHandover({...body,received:false})).toThrow();for(const check_id of ['domestic','export','document_mail'])expect(()=>parseHandover({...body,check_id})).toThrow();expect(parseHandover({...body,check_id:'domestic',reference_id:id,received:false}).p_reference).toBe(id);expect(parseHandover({...body,result:'blocked',received:false}).p_received).toBe(false);});
test('anonymous or denied actor cannot inspect/update review records',async()=>{jest.mocked(opsStaff).mockRejectedValue(new ApiError(403,'denied'));expect((await GET(new Request('https://example.invalid'))).status).toBe(403);expect((await PUT(request())).status).toBe(403);expect(supabaseAdmin.rpc).not.toHaveBeenCalled();});
test('save binds real actor and rate limits without changing trading controls',async()=>{const r=await PUT(request());expect(r.status).toBe(200);expect(r.headers.get('cache-control')).toBe('no-store');expect(rateLimit).toHaveBeenCalledWith(expect.any(Request),'handover-review',30,900,id);expect(supabaseAdmin.rpc).toHaveBeenCalledTimes(1);expect(supabaseAdmin.rpc).toHaveBeenCalledWith('b2b_save_handover',{p_actor:id,...parseHandover(body)});});
test.each([['40001',409],['42501',403],['22023',400],['private',503]])('DB %s maps safely',async(code,status)=>{jest.mocked(supabaseAdmin.rpc).mockResolvedValue({error:{code,message:'private provider secret'}} as never);const r=await PUT(request());expect(r.status).toBe(status);expect(await r.text()).not.toContain('provider secret');});
test('failed source read fails closed, limited roles never retrieve launch data',async()=>{jest.mocked(supabaseAdmin.rpc).mockResolvedValue({data:null,error:{}} as never);await expect(handoverSnapshot(id)).rejects.toMatchObject({status:503});jest.mocked(supabaseAdmin.rpc).mockResolvedValue({data:{...data,role:'product_staff'},error:null} as never);const d=await handoverSnapshot(id);expect(d.assessment).toBeUndefined();expect(launchStatus).not.toHaveBeenCalled();});
test('each active employee must personally attest access and mail; stale/blocked reviews never pass',()=>{
 const checks=['business','prices','bank','owner','incidents','fx','issuer','storage','notification','release'].map(id=>({id,title:id,href:'/',detail:'',ready:true}));
 const reviews=HANDOVER_CHECKS.map(c=>({check_id:c.id,staff_id:id,result:'passed',current:true,revision:1,notes:'Checked evidence',reference_id:null,received:true,basis:hash,reviewed_at:'2026-10-04'})) as HandoverData['reviews'];
 const products=[{product_id:'p',name:'P',sku:'P',fingerprint:hash,domestic_issues:[],export_issues:[],review:{fingerprint:hash,domestic:true,export:true,revision:1,reason:'Checked evidence',reviewed_at:'2026-10-04'}}];
 const pass={...data,reviews};expect(assessHandover(pass,checks,controls,products).domestic.ready).toBe(true);expect(assessHandover(pass,checks,controls,products).export.ready).toBe(true);
 expect(assessHandover({...pass,staff:[...data.staff,{id:'second',name:'Second',role:'product_staff'}]},checks,controls,products).domestic.ready).toBe(false);
 expect(assessHandover({...pass,reviews:reviews.map(r=>r.check_id==='domestic'?{...r,current:false}:r)},checks,controls,products).domestic.ready).toBe(false);
 expect(assessHandover(pass,checks,{...controls,pi_paused:true},products).export.ready).toBe(false);
 expect(assessHandover(pass,checks,controls,products.map(p=>({...p,domestic_issues:['expired']}))).domestic.ready).toBe(false);
 expect(assessHandover(pass,checks.filter(c=>c.id!=='bank'),controls,products).domestic.ready).toBe(false);
});
test('export-only released SKU never completes domestic release condition',()=>{const x=assessHandover(data,[],controls,[]);expect(x.domestic.ready).toBe(false);expect(x.export.ready).toBe(false);expect(x.domestic.gaps).toContain('승인 상품 거래 제한 활성화');});
test('fixed database errors do not include details',()=>{expect(()=>handoverError(null)).not.toThrow();expect(()=>handoverError({code:'unknown'})).toThrow(ApiError);});
