'use client';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {HANDOVER_CHECKS,canReview,type HandoverData,type HandoverKey} from '@/lib/launch/handover';
export default function HandoverManager(){
 const [data,setData]=useState<HandoverData|null>(null),[selected,setSelected]=useState<HandoverKey|null>(null),[result,setResult]=useState<'passed'|'blocked'>('blocked'),[notes,setNotes]=useState(''),[reference,setReference]=useState(''),[received,setReceived]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState('');
 const alert=useRef<HTMLParagraphElement>(null);
 async function load(){const r=await fetch('/api/admin/handover',{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error||'인수 자료 조회 실패');setData(d);}
 useEffect(()=>{let active=true;fetch('/api/admin/handover',{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);if(active)setData(d);}).catch(()=>{if(active)setError('업무 인수 자료를 불러오지 못했습니다. 다시 시도해 주세요.');});return()=>{active=false;};},[]);
 useEffect(()=>{if(error)alert.current?.focus();},[error]);
 async function refresh(){setBusy(true);setError('');try{await load();setSelected(null);}catch{setError('업무 인수 자료를 불러오지 못했습니다.');}finally{setBusy(false);}}
 async function save(e:React.FormEvent){e.preventDefault();if(!data||!selected||busy)return;setBusy(true);setError('');setSaved('');
 try{const current=data.reviews.find(r=>r.staff_id===data.actor_id&&r.check_id===selected),r=await fetch('/api/admin/handover',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({check_id:selected,revision:current?.revision||0,basis:data.basis[selected],result,notes,reference_id:reference.trim()||null,received})}),d=await r.json();if(!r.ok)throw Error(d.error);await load();setSelected(null);setSaved('내 업무 인수 검수 기록을 저장했습니다. 거래 접수·출시 제한 설정은 변경하지 않습니다.');}
 catch(e){setError(e instanceof Error?e.message:'검수 저장 실패');}finally{setBusy(false);}}
 return <div className="mt-6 space-y-6">
 <p className="leading-7">등록된 직원이 자신의 계정으로 수행한 검수와 근거를 기록합니다. 다른 직원의 결과를 대신 확인할 수 없습니다. 회사·상품·가격·계좌·PI 조건·담당자 변경은 업무 재검수를, 직원 권한 변경은 해당 직원의 재검수를 요구합니다.</p>
 <p className="leading-7">이 화면은 제한 출시 준비 판정입니다. 실제 공개와 거래 설정은 <Link href="/admin/releases" className="underline">출시 상품 검수</Link> 및 <Link href="/admin/launch" className="underline">오픈 점검·서비스 중지</Link>에서 관리합니다. 무료 환경의 독립 스테이징·전체 복구·배포 원복 검수는 별도 미완료 항목으로 유지합니다.</p>
 {error&&<p ref={alert} role="alert" tabIndex={-1} className="rounded border border-red-500 bg-white p-4 text-red-800">{error}</p>}
 {saved&&<p role="status" className="text-green-900">{saved}</p>}
 <button disabled={busy} onClick={()=>void refresh()} className="min-h-11 rounded border bg-white px-4">최신 인수 상태 불러오기</button>
 {data?<>{data.assessment&&<section className="grid gap-4 lg:grid-cols-2" aria-label="국내·해외 제한 출시 판정">{(['domestic','export'] as const).map(mode=><article key={mode} className="rounded-xl border bg-white p-5"><h2 className="text-xl font-bold">{mode==='domestic'?'국내':'해외'} 제한 출시 준비</h2><p className="mt-3 font-semibold">{data.assessment![mode].ready?'조건 충족 · 운영자의 제한 공개 검토 가능':'보류 · 아래 인수 조건 확인 필요'}</p><ul className="mt-3 list-disc space-y-2 pl-5">{data.assessment![mode].gaps.map(g=><li key={g}>{g}</li>)}</ul></article>)}</section>}
 <section className="rounded-xl border bg-white p-5"><h2 className="text-xl font-bold">직원별 인수 현황</h2><ul className="mt-3 space-y-3">{data.staff.map(s=><li key={s.id} className="rounded border p-3"><p className="font-semibold">{s.name} · {s.role}</p><p className="mt-2">{data.reviews.filter(r=>r.staff_id===s.id&&r.result==='passed'&&r.current).length}개 현재 검수 완료 · 로그인 권한 및 인증 메일은 직원마다 확인</p></li>)}</ul></section>
 <section className="space-y-3"><h2 className="text-xl font-bold">내 업무 검수</h2>{HANDOVER_CHECKS.filter(c=>canReview(c.id,data.role)).map(c=>{const review=data.reviews.find(r=>r.staff_id===data.actor_id&&r.check_id===c.id);return <article key={c.id} className="space-y-3 rounded-xl border bg-white p-5"><h3 className="text-lg font-bold">{c.title}</h3><p>{!review?'미확인':!review.current?'자료 변경·근거 상태 변경 · 재검수 필요':review.result==='passed'?'검수 완료 · 운영자 확인':'미완료·문제 확인'}</p><p className="leading-7">{c.detail}</p>{review&&<p className="break-words text-sm">{review.notes} · {new Date(review.reviewed_at).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})} KST</p>}<div className="flex flex-wrap gap-4"><Link href={c.href} className="underline">관련 관리자 화면</Link><button disabled={busy} onClick={()=>{setSelected(c.id);setResult('blocked');setNotes('');setReference('');setReceived(false);setSaved('');setError('');}} className="min-h-11 rounded border px-4">{c.title} 결과 기록</button></div></article>;})}</section>
 {selected&&<form onSubmit={save} className="space-y-4 rounded-xl border-2 border-green-900 bg-white p-5"><h2 className="text-xl font-bold">{HANDOVER_CHECKS.find(c=>c.id===selected)!.title} 결과 입력</h2>
 <label className="block">검수 결과<select aria-label="검수 결과" value={result} onChange={e=>setResult(e.target.value as 'passed'|'blocked')} className="mt-2 w-full rounded border p-3"><option value="blocked">미완료·문제 확인</option><option value="passed">실제 검수 완료</option></select></label>
 {['domestic','export','document_mail'].includes(selected)&&<label className="block">실제 거래·알림 ID<input aria-label="실제 거래·알림 ID" required={result==='passed'} value={reference} onChange={e=>setReference(e.target.value)} maxLength={36} className="mt-2 w-full rounded border p-3"/><span className="mt-2 block text-sm">주문·CRM 상세 주소의 주문/PI ID 또는 이메일 운영의 알림 ID를 사용합니다.</span></label>}
 {['auth_mail','document_mail'].includes(selected)&&<label className="flex min-h-11 items-center gap-3"><input type="checkbox" required={result==='passed'} checked={received} onChange={e=>setReceived(e.target.checked)}/>실제 받은편지함·스팸함 수신과 링크 접근을 직접 확인했습니다</label>}
 <label className="block">검수 근거·미완료 사유<textarea aria-label="검수 근거·미완료 사유" required minLength={10} maxLength={1500} value={notes} onChange={e=>setNotes(e.target.value)} rows={4} className="mt-2 w-full rounded border p-3"/></label><p className="text-sm">검수 방법·결과·확인 날짜를 남깁니다. 비밀번호·API 키·고객 개인정보 원문을 입력하지 마세요. 서버가 현재 자료 버전과 실제 거래 상태를 확인합니다.</p>
 <div className="flex flex-wrap gap-3"><button disabled={busy} className="min-h-11 rounded bg-green-900 px-5 py-3 text-white">내 검수 기록 저장</button><button type="button" disabled={busy} onClick={()=>setSelected(null)} className="min-h-11 rounded border px-5">닫기</button></div></form>}
 <section className="rounded-xl border bg-white p-5"><h2 className="text-xl font-bold">최근 인수 검수 이력</h2>{data.events.length?<ul className="mt-4 space-y-3">{data.events.map(e=><li key={e.id} className="break-words border-b pb-3 text-sm">{data.staff.find(s=>s.id===e.staff_id)?.name||'이전 직원'} · {HANDOVER_CHECKS.find(c=>c.id===e.check_id)?.title} · {e.result==='passed'?'확인':'미완료'} · {e.notes} · {new Date(e.created_at).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})} KST</li>)}</ul>:<p className="mt-3">저장된 실제 인수 검수 기록이 없습니다.</p>}</section></>:!error&&<p role="status">업무 인수 자료 확인 중…</p>}
 </div>;
}
