'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import type {LaunchStatus,ServiceState} from '@/lib/launch/types';
const scopes=[['inquiries_paused','신규 RFQ·국내 구매 문의'],['orders_paused','신규 국내 주문'],['pi_paused','신규 PI 발행']] as const;
export default function LaunchManager(){
 const [data,setData]=useState<LaunchStatus|null>(null),[draft,setDraft]=useState<ServiceState|null>(null),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState('');
 const alert=useRef<HTMLParagraphElement>(null);
 async function load(){setBusy(true);setError('');try{const r=await fetch('/api/admin/launch',{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error);setData(d);const c=d.controls;setDraft({inquiries_paused:c.inquiries_paused,orders_paused:c.orders_paused,pi_paused:c.pi_paused,owner_id:c.owner_id??null,response_minutes:c.response_minutes});}catch(e){setError(e instanceof Error?e.message:'점검 자료를 불러오지 못했습니다.');}finally{setBusy(false);}}
 useEffect(()=>{let live=true;fetch('/api/admin/launch',{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);if(live){setData(d);const c=d.controls;setDraft({inquiries_paused:c.inquiries_paused,orders_paused:c.orders_paused,pi_paused:c.pi_paused,owner_id:c.owner_id??null,response_minutes:c.response_minutes});}}).catch(()=>{if(live)setError('점검 자료를 불러오지 못했습니다. 다시 시도해 주세요.');});return()=>{live=false;};},[]);
 useEffect(()=>{if(error)alert.current?.focus();},[error]);
 async function save(e:React.FormEvent){e.preventDefault();if(!data||!draft||busy)return;setBusy(true);setError('');setSaved('');
 try{const r=await fetch('/api/admin/launch',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:data.controls.revision,state:draft,reason})}),d=await r.json();if(!r.ok)throw new Error(d.error);setReason('');setSaved('운영 상태를 저장했습니다. 신규 접수에 즉시 적용되며 변경 이력이 남습니다.');await load();}
 catch(e){setError(e instanceof Error?e.message:'저장하지 못했습니다.');}finally{setBusy(false);}}
 return <div className="mt-6 space-y-6"><p className="leading-7">자동 점검은 상업 오픈 승인이 아닙니다. 아래 자료와 실제 스테이징·복구 검증을 운영자가 확인해야 합니다. 상품의 미승인 가격은 주문·PI 발행에 사용할 수 없습니다.</p>
 {error&&<p ref={alert} role="alert" tabIndex={-1} className="rounded border border-red-400 bg-white p-4 text-red-800">{error}</p>}{saved&&<p role="status" className="text-green-900">{saved}</p>}
 <p><Link href="/admin/handover" className="underline">직원 업무 인수·국내/해외 제한 출시 판정</Link></p>
 <button disabled={busy} onClick={()=>void load()} className="min-h-11 rounded border bg-white px-4">최신 상태 불러오기</button>
 {data&&draft?<><section className="rounded-xl border bg-white p-5"><h2 className="text-xl font-bold">오픈 전 확인 항목</h2><p className="my-3 text-sm">자동 항목 {data.checks.filter(c=>c.ready).length}/{data.checks.length}개 확인 · 수동 검수 기록 필요</p><ul className="space-y-3">{data.checks.map(c=><li key={c.id} className="rounded border p-3"><Link href={c.href} className="font-bold underline">{c.title}</Link><span className={c.ready?'ml-3 text-green-900':'ml-3 text-red-800'}>{c.ready?'입력·연결 확인':'확인 필요'}</span><p className="mt-2 break-words text-sm leading-6">{c.detail}</p></li>)}</ul><h3 className="mt-6 font-bold">별도 검수 기록</h3><ul className="mt-3 list-disc space-y-2 pl-5 text-sm leading-6">{data.manual_checks.map(t=><li key={t}>{t}</li>)}</ul><p className="mt-4 text-xs">조회 시각: {data.facts.checked_at}</p></section>
 <section className="rounded-xl border bg-white p-5"><h2 className="text-xl font-bold">장애 대응·신규 거래 중지</h2><p className="mt-3 text-sm leading-7">체크하면 해당 신규 접수가 중지됩니다. 기존 접수의 조회·다운로드·같은 요청 키 재시도와 이미 시작된 발행의 복구는 유지됩니다. 읽기 장애·정보 노출 사고는 별도 배포 원복과 키·세션 대응이 필요합니다.</p><form onSubmit={save} className="mt-5 space-y-5"><div className="space-y-3">{scopes.map(([k,label])=><label key={k} className="flex min-h-11 items-center gap-3"><input type="checkbox" checked={draft[k]} onChange={e=>setDraft({...draft,[k]:e.target.checked})}/>{label} 중지</label>)}</div>
 <label className="block">운영 책임자·대응 담당자<select aria-label="운영 책임자·대응 담당자" value={draft.owner_id??''} onChange={e=>setDraft({...draft,owner_id:e.target.value||null})} className="mt-2 w-full rounded border p-3"><option value="">미지정</option>{(data.staff||[]).map(s=><option key={s.id} value={s.id}>{s.name} · {s.email}</option>)}</select></label><p className="text-sm leading-6">등록된 활성 직원 중에서 지정합니다. 직원 이름이 바뀌면 표시를 갱신하고, 정지·삭제 시 지정이 해제됩니다. <Link href="/admin/users" className="underline">하위관리자 관리</Link></p>
 <label className="block">장애 확인 후 대응 목표 (분, 5~1,440)<input type="number" min={5} max={1440} step={1} value={draft.response_minutes??''} onChange={e=>setDraft({...draft,response_minutes:e.target.value===''?null:Number(e.target.value)})} className="mt-2 w-full rounded border p-3"/></label>
 <label className="block">중지·재개 또는 담당자 변경 사유 *<textarea required minLength={3} maxLength={500} rows={3} value={reason} onChange={e=>setReason(e.target.value)} className="mt-2 w-full rounded border p-3"/></label>
 <button disabled={busy} className="min-h-11 rounded bg-green-900 px-5 py-3 text-white">{busy?'처리 중…':'운영 상태 저장'}</button></form></section>
 <section className="rounded-xl border bg-white p-5"><h2 className="text-xl font-bold">최근 중지·재개 이력</h2>{data.events.length?<ul className="mt-4 space-y-4">{data.events.map(e=><li key={e.revision} className="break-words border-b pb-3 text-sm"><p>{e.created_at} · 버전 {e.revision} · {e.reason}</p><p className="mt-2">{scopes.map(([k,label])=>label+': '+(e.before_state[k]?'중지':'접수')+' → '+(e.after_state[k]?'중지':'접수')).join(' / ')}</p></li>)}</ul>:<p className="mt-3 text-sm">저장된 변경 이력이 없습니다.</p>}</section></>:!error&&<p role="status">실제 운영 상태 확인 중…</p>}</div>;
}
