import {serverLanguage} from '@/lib/i18n/server';
import {getBusinessSettings} from '@/lib/business-settings-server';
import BusinessContact from '@/components/layout/BusinessContact';
export default async function PolicyPage({kind}:{kind:'terms'|'privacy'}){
 const {language,text}=await serverLanguage(),{profile}=await getBusinessSettings(),privacy=kind==='privacy';
 const shipping=language==='en'?profile.shipping_en:profile.shipping_ko,returns=language==='en'?profile.returns_en:profile.returns_ko,detail=language==='en'?profile.privacy_en:profile.privacy_ko;
 const sections=privacy?[
 [text('수집 항목과 이용 목적','Data and purposes'),text('이메일은 가입·인증·계정 확인에 사용합니다. 문의·주문 시 입력한 이름·전화번호·회사 정보·배송지·문의 내용은 견적, 공급 조건 확인, 배송 및 고객 응대에 사용합니다. 회사 정보와 사업자번호는 가입 필수 항목이 아닙니다.','Email is used for registration, verification and account access. Names, phone numbers, optional company details, delivery addresses and enquiry content are used for quotations, supply review, delivery and customer support. Company details and business registration are optional at signup.')],
 [text('계정·저장 정보','Account and browser storage'),text('인증 세션은 보안 쿠키로 유지됩니다. 브라우저에는 언어 선택과 구매함·RFQ 선택 상품·관심 상품을 저장할 수 있습니다. 공용 기기에서는 로그아웃하고 저장된 선택 항목을 지워 주세요.','Authentication sessions use secure cookies. Your browser may retain language preferences, cart/RFQ selections and favourites. Sign out and clear saved selections on shared devices.')],
 [text('보유기간·처리 서비스·이용자 권리','Retention, service providers and your rights'),detail||text('운영자가 보유기간, 처리 위탁·국외 이전의 해당 여부와 세부사항, 열람·정정·삭제·처리정지 요청 절차를 확인 중입니다. 확인 전에는 최종 개인정보처리방침으로 확정하지 않습니다. 관련 요청은 아래 문의처로 보내 주세요.','The operator is confirming retention periods, service-provider and international-transfer details, and procedures for access, correction, deletion and restriction requests. This notice is not a finalized privacy policy until these details are confirmed. Please contact us below for requests.')],
 [text('개인정보 문의','Privacy enquiries'),profile.privacy_contact||text('개인정보 담당자 정보 확인 중입니다. 아래 고객 문의처에서 관련 요청을 접수합니다.','The designated privacy contact is being confirmed. Requests can be submitted to the contact below.')]
 ]:[
 [text('가입과 구매 대상','Membership and purchasing'),text('개인과 사업자 모두 이메일 인증 후 별도 가입 승인 없이 이용할 수 있습니다. 사업자번호 입력은 선택입니다. 회사별 계약 가격 등 별도 거래 조건은 담당자 확인이 필요합니다.','Individuals and businesses can join after email verification without a separate signup approval. Business registration is optional. Company-specific contract prices and other trade terms require review.')],
 [text('가격·주문·입금','Prices, orders and payment'),text('상품별 포장 단위와 최소수량을 확인하세요. 국내 금액은 공급가와 VAT를 구분합니다. 주문 요청 후 담당자가 배송비와 공급 조건을 검토하며, 고객이 확정된 조건을 수락한 뒤 계좌 입금을 안내합니다. 카드 결제는 제공하지 않습니다.','Check packaging and minimum quantities for each product. Domestic prices distinguish net amounts and VAT. Staff review delivery fees and supply terms after an order request. Bank-transfer instructions follow your acceptance of the confirmed terms. Card payments are not offered.')],
 ['Export RFQ / Proforma Invoice',text('해외 기준가는 국내 도매가의 VAT 10%를 제외한 FOB 기준입니다. 국내 운송·수출통관·본선 적재 비용을 포함하여 운영하되, 수량·항구·선적 조건에 따라 조정될 수 있습니다. RFQ는 주문·결제 완료가 아니며 Proforma Invoice는 최종 Commercial Invoice가 아닙니다.','Export reference prices exclude 10% Korean VAT and use FOB terms, including domestic transport, export clearance and loading costs. Prices may be adjusted for quantity, port and shipment requirements. An RFQ is not a completed order or payment. A Proforma Invoice is not a final Commercial Invoice.')],
 [text('배송 기준','Delivery'),shipping||text('상품의 보관 온도, 수량, 수령지에 따라 담당자가 배송 방법·비용·예정일을 확인합니다. 정액 배송비·무료배송·당일출고는 일괄 보장하지 않습니다. 상세 운영 기준은 확인 중입니다.','Staff confirm shipping method, cost and estimated date based on storage requirements, quantity and destination. Flat-rate shipping, free shipping and same-day dispatch are not guaranteed. Detailed operating terms are being confirmed.')],
 [text('취소·반품','Cancellation and returns'),returns||text('취소·파손·오배송·품질 문제는 주문 상세의 요청 기능 또는 아래 문의처로 접수하세요. 반품지·회수 방법·비용 부담 기준은 확인 중이며, 소비자에게 적용되는 법정 권리를 제한하지 않습니다.','Report cancellation requests, damage, incorrect deliveries or quality issues through the order detail page or the contact below. Return address, collection and cost-allocation procedures are being confirmed. Applicable statutory consumer rights are not restricted.')],
 [text('상품 정보와 공급 제한','Product information and supply restrictions'),text('원산지·성분·알레르기·인증·유통기한은 상품별 표시와 확인 자료를 기준으로 안내합니다. 모든 상품이 동일 인증을 가진 것으로 안내하지 않습니다. 주류 등 제한 상품은 판매 자격·성인 확인 및 도착국 규정 검토가 필요합니다.','Origin, ingredients, allergens, certifications and shelf life depend on each product and its supporting documents. Certification is not assumed across all products. Restricted goods, including alcohol, require review of seller eligibility, age verification and destination rules.')]
 ];
 const pending=privacy?!detail||!profile.privacy_contact:!shipping||!returns||!profile.owner||!profile.registration||!profile.address||!profile.ecommerce_registration;
 return <main className="mx-auto max-w-4xl px-5 py-12"><h1 className="text-3xl font-bold">{privacy?text('개인정보 처리 안내','Privacy notice'):text('이용·거래 안내','Terms and trading information')}</h1>
 {pending&&<p className="mt-6 rounded border border-amber-400 bg-amber-50 p-4 text-sm leading-7">{text('현재 운영자가 세부 정보를 확인 중인 안내입니다. 미확정 항목은 확인 후 갱신하며, 정식 운영 검수에 포함됩니다.','Some operating details are still under review. Unconfirmed items will be updated and checked before full launch.')}</p>}
 <div className="mt-8 space-y-8">{sections.map(([title,body])=><section key={title}><h2 className="text-xl font-bold">{title}</h2><p className="mt-3 whitespace-pre-wrap break-words leading-8">{body}</p></section>)}</div><section className="mt-10 border-t pt-6"><h2 className="text-xl font-bold">{text('회사·문의 정보','Business and contact details')}</h2><BusinessContact profile={profile} language={language}/></section></main>;
}
